[build]
  command = "cd frontend && npm install --no-fund --no-audit --loglevel=error && npm run build"
  publish = "frontend/build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
  CI = "false"
